version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - "stats-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  main-service:
    build: main-service/
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
    - POSTGRES_DB=main
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    depends_on:
      - "ewm-db"
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin